apiVersion: v1
kind: Pod
metadata:
  name: broken-pod
  namespace: talium
spec:
  containers:
    - name: app
      image: nginx:alpine
      resources:
        requests:
          memory: "250mi"
          cpu: "250m"

