apiVersion: v1
kind: Service
metadata:
  name: talium-api
  namespace: talium
spec:
  type: ClusterIP
  selector:
    app: talium-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
