apiVersion: v1
kind: ConfigMap
metadata:
  name: talium-config
  namespace: talium
data:
  DB_HOST: "db"
  DB_NAME: "talium"
  DB_USER: "admin"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  FLASK_ENV: "production"
  LOG_LEVEL: "info"
