apiVersion: apps/v1
kind: Deployment
metadata:
  name: talium-api
  namespace: talium
  labels:
    app: talium-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: talium-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: talium-api
    spec:
      containers:
        - name: talium-api
          image: taliumt/talium-care-api:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
